FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y 

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 hacker 

RUN  echo 'hacker:abcde' | chpasswd

RUN service ssh start

EXPOSE 22

RUN cd && mkdir /home/ubuntu/LinuxDiary2021

WORKDIR  /home/ubuntu/LinuxDiary2021

RUN echo "r89ehg8reghre8gh89rehg89rehg8rehgrehg9erhg9hre9ghre9hgr98hg8hihioihiohoihihihhoihi 9hr89hrue78gugewf3fwg\njegh894h894h89gh89ehrg8h gr89hge89rhg89erhg89ehg89gh9r8egherhg89hehnoihihihihjihoihii ehgrfgrregreg egegewgegergkpok pokokpok okpokrgregregre9e8ghr89ehgrheg9rehgh84f894h">.itmaybehere00

RUN echo "r89ehg8reghre8gh89rehg89rehg8rehgrehg9erhg9hre9ghre9hgr98hg8hihioihiohoihihihhoihi 9hr89hrue78gugewf3fwg\njegh894h894h89gh89ehrg8h gr89hge89rhg89erhg89ehg89gh9etet43t34trfg grgeger4t3ojgjgoijegjeojgejgerjgijoijr8egherhg89hehnoihihihihjihoihii ehgrfgrregreg egegewgegergkpok pokokpok okpokrgregregre9e8ghr89ehgrheg9reweqwhgh84f894h">.itmaybehere01

RUN echo "r89ehg8reghre8gh89rehg89rehg8rehgrehg9erhg9hre9ghre9hgr98hg8hihioihiohoihihihhoihi 9hr89hrue78gugewf3fwg\njegh894h894h89gh89ehrg8h gr89hge89rhg89erhg89ehg89gh9rgjroirieiorhegioregihriehhgh84f894h">.itmaybehere02

RUN echo "hfoewheiwhfihw893hfiwefwhewhiwgheghyewgewguewgew\nrhq89rh78qrg7q3g3gr367g276rg3276gr3276rg2673gf rejgergjreooigjregjigjeoigjgrgrej89hg89ehrg8h gr89hge89rhg89erhg89ehg89gh9r8egherhg89hehnoihihihihjihoihii ehgr9e8ghr89ehgrheg9rehgr89ehg8reghre8gh89rehg89rehg8rehgrehg9erhg9hre9ghre9hgr98hg8hihioihiohoihihihhoihi 9hr89hrue78gugewf3fwg\njegh894h894h89gh8hf849th84f894h">.itmaybehere04

RUN echo "\n\nCongratulations, You are on right track :) \n\nFollow given steps to complete the task -> \n\n1.Use following string as str1 -> ILoveLinux\n2.Now, print current woking directory.\n3.Use this output as str2\n4.Concatinate str1 and str2(i.e. str1 + str2) \n5.Submit the resultant string in provided google form \n\nIf required always do take help of our best friend => Google :)\n\n\n\n\nGoogle Form Link : https://forms.gle/JaDCy5GRwWdcagz27 \n\n"> .itmaybehere03

RUN sudo chmod 444 .itmaybehere00

RUN sudo chmod 444 .itmaybehere01

RUN sudo chmod 444 .itmaybehere02

RUN sudo chmod 444 .itmaybehere03

RUN sudo chmod 444 .itmaybehere04

WORKDIR /home

CMD ["/usr/sbin/sshd","-D"]
