FROM ubuntu:latest

RUN apt update && apt install  openssh-server sudo -y

RUN adduser hacker 

RUN echo 'root:iKD2YZmKB4' | chpasswd

RUN  echo 'hacker:abcde' | chpasswd

RUN service ssh start

EXPOSE 22

WORKDIR /home/hacker

RUN mkdir LinuxDiary2021

RUN cd LinuxDiary2021

RUN mkdir firstDIR

RUN mkdir secondDIR

RUN mkdir thirdDIR

RUN mkdir forthDIR

RUN mkdir fifthDIR

RUN cd firstDIR

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere00

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere01

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere02

RUN echo "\n\n\nThe solution for the this is stored in the file .itmaybehere00 present in fifthDIR  directory, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.\nYou have to find original string and submit in provided google form\n\n\n\n\nRotation by 13 -> ThisIsWrongFile..SeeGivenConditions\n\n\n\nGoogle Form -> ThisIsWrongFile..SeeGivenConditions" > .itmaybehere03

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere04

RUN chmod 544 .itmaybehere02

RUN chmod 444 .itmaybehere04

RUN chmod 554 .itmaybehere01

RUN chmod 777 .itmaybehere00

RUN chmod 574 .itmaybehere03

RUN cd ../secondDIR

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere00

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere01

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere02

RUN echo "Gur cnffjbeq vf 5Gr8L4qetPEsPk8htqjhRK8XSP6x2RHh" > .itmaybehere03

RUN echo "\n\n\nThe solution for the this is stored in the file .itmaybehere00 present in fifthDIR  directory, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.\nYou have to find original string and submit in provided google form\n\n\n\n\nRotation by 13 -> ThisIsWrongFile..SeeGivenConditions\n\n\n\nGoogle Form -> ThisIsWrongFile..SeeGivenConditions" > .itmaybehere04

RUN chmod 544 .itmaybehere00

RUN chmod 444 .itmaybehere01

RUN chmod 554 .itmaybehere02

RUN chmod 777 .itmaybehere03

RUN chmod 574 .itmaybehere04

RUN cd ../thirdDIR

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere00

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere01

RUN echo "\n\n\nThe solution for the this is stored in the file .itmaybehere00 present in fifthDIR  directory, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.\nYou have to find original string and submit in provided google form\n\n\n\n\nRotation by 13 -> ThisIsWrongFile..SeeGivenConditions\n\n\n\nGoogle Form -> ThisIsWrongFile..SeeGivenConditions" > .itmaybehere02

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere03

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere04

RUN chmod 544 .itmaybehere04

RUN chmod 444 .itmaybehere03

RUN chmod 554 .itmaybehere02

RUN chmod 777 .itmaybehere00

RUN chmod 574 .itmaybehere01

RUN cd ../forthDIR

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere00

RUN echo "\n\n\nThe solution for the this is stored in the file .itmaybehere03 present in secondDIR directory, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.\nYou have to find original string and submit in provided google form\n\n\n\n\nRotation by 13 -> https://en.wikipedia.org/wiki/ROT13\n\n\n\nGoogle Form -> https://forms.gle/xZmrkPJSrGtbsupA6" > .itmaybehere01

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere02

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere03

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere04

RUN chmod 544 .itmaybehere01

RUN chmod 444 .itmaybehere00

RUN chmod 554 .itmaybehere02

RUN chmod 777 .itmaybehere03

RUN chmod 574 .itmaybehere04

RUN cd ../fifthDIR

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere00

RUN echo "\n\n\nThe solution for the this is stored in the file .itmaybehere00 present in fifthDIR  directory, where all lowercase (a-z) and uppercase (A-Z) letters have been rotated by 13 positions.\nYou have to find original string and submit in provided google form\n\n\n\n\nRotation by 13 -> ThisIsWrongFile..SeeGivenConditions\n\n\n\nGoogle Form -> ThisIsWrongFile..SeeGivenConditions" > .itmaybehere01
                                                  
RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere02

RUN echo "grgegergergegggv gr rejj jjpwjfpjepjf wpjfpeojpp" > .itmaybehere03

RUN echo "Linux was originally developed for personal computers based on the Intel x86 architecture, but has since been ported to more platforms than any other operating system.[20] Because of the dominance of the Linux-based Android on smartphones, Linux also has the largest installed base of all general-purpose operating systems.[21][22][23][24] Although it is used by only around 2.3 percent of desktop computers,[25][26] the Chromebook, which runs the Linux kernel-based Chrome OS, dominates the US K–12 education market and represents nearly 20 percent of sub-$300 notebook sales in the US.[27] Linux is the leading operating system on servers (over 96.4% of the top 1 million web servers' operating systems are Linux),[28] leads other big iron systems such as mainframe computers, and is the only OS used on TOP500 supercomputers (since November 2017, having gradually eliminated all competitors)" > .itmaybehere04

RUN chmod 544 .itmaybehere04

RUN chmod 444 .itmaybehere01

RUN chmod 554 .itmaybehere00

RUN chmod 777 .itmaybehere03

RUN chmod 574 .itmaybehere02

RUN cd ../

RUN echo "\n\n\n1) At Start You will be inside /LinuxDiary2021 directory.\n2) Now, here you have to find a file with following constraints\n     i.The file should be of size 367 Bytes \n     ii.The file have reading permission for anyone but , execution only for owner\n3) Find the file with given constraints, there you will get further instructions \n\n\nGook Luck:)\n\n\nAuthor:Pavan Shinde, Program Director WLUG" > README

CMD ["/usr/sbin/sshd","-D"]
